<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'kornrunner\\Ethereum\\' => array($vendorDir . '/kornrunner/ethereum-address/src'),
    'kornrunner\\' => array($vendorDir . '/kornrunner/ethereum-offline-raw-tx/src', $vendorDir . '/kornrunner/keccak/src', $vendorDir . '/kornrunner/secp256k1/src'),
    'Web3p\\RLP\\' => array($vendorDir . '/web3p/rlp/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Mdanter\\Ecc\\' => array($vendorDir . '/mdanter/ecc/src'),
    'FG\\' => array($vendorDir . '/fgrosse/phpasn1/lib'),
);
