<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'fgrosse/phpasn1' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fgrosse/phpasn1',
            'aliases' => array(),
            'reference' => 'eef488991d53e58e60c9554b09b1201ca5ba9296',
            'dev_requirement' => false,
        ),
        'kornrunner/ethereum-address' => array(
            'pretty_version' => 'v0.3.0',
            'version' => '0.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kornrunner/ethereum-address',
            'aliases' => array(),
            'reference' => '89197ed3992d74f0de76702cd82ec32d1264dad9',
            'dev_requirement' => false,
        ),
        'kornrunner/ethereum-offline-raw-tx' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kornrunner/ethereum-offline-raw-tx',
            'aliases' => array(),
            'reference' => '2665fc539bad911e337def3b6e518505369286aa',
            'dev_requirement' => false,
        ),
        'kornrunner/keccak' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kornrunner/keccak',
            'aliases' => array(),
            'reference' => '433749d28e117fb97baf9f2631b92b5d9ab3c890',
            'dev_requirement' => false,
        ),
        'kornrunner/secp256k1' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kornrunner/secp256k1',
            'aliases' => array(),
            'reference' => 'c3990dba47c7a8b0c9fd858fb29c61a5794fbb39',
            'dev_requirement' => false,
        ),
        'mdanter/ecc' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mdanter/ecc',
            'aliases' => array(),
            'reference' => '34e2eec096bf3dcda814e8f66dd91ae87a2db7cd',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '0abb51d2f102e00a4eefcf46ba7fec406d245825',
            'dev_requirement' => false,
        ),
        'web3p/rlp' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web3p/rlp',
            'aliases' => array(),
            'reference' => '1653af23142863b490bdf22c6d0335bdb588c983',
            'dev_requirement' => false,
        ),
    ),
);
